modLoader = "javafml"
loaderVersion = "[2,)"

license = "MIT"

[[mods]]
modId = "ethereal_arc"
version = "0.0.0"
displayName = "Ethereal Arc"
authors = "Ernerg"
description = '''
A survival-friendly builder-oriented expansion mod
mixing magic and technology to let you enhance your
world’s atmosphere and gameplay.
'''

# === Dependencies ===
[[dependencies.ethereal_arc]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ethereal_arc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"
